services:
  - type: web
    name: web-round2
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix client && npm install --prefix server && npm run build --prefix client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
